spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hastorage?useSSL=false
    username: sanya
    password: passWd1984!
  jpa:
    hibernate:
      ddl-auto: none

someParameter:
  value: 5463