server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5454/hastorage
    username: sanya
    password: passWd1984!

  iquibase:
    change-log: classpath:liquibase/changelog.xml
    enabled: true

someParameter:
  value: 5463
